class OdfDF:
    
        siren="siren"
        nom="nom"
        type="type"
        regcode="regcode"
        url_ptf="url_ptf"
        nb_ptf="nb_ptf"
        url_datagouv="url_datagouv"
        nb_datagouv="nb_datagouv"
        id_datagouv="id_datagouv"
        id_ods="id_ods"
        pop_insee="pop_insee"
        lat="lat"
        long="long"
        merge="merge"
        depcode="depcode"
        ptf="ptf"
        theme="thématiques"